export type IconItem = { name: string; label: string };
export type IconGroup = { group: string; items: IconItem[] };

/** Расширенный набор lucide-иконок для инструментов и сервисов, сгруппированный по темам. */
export const ICON_GROUPS: IconGroup[] = [
  {
    group: "Работа",
    items: [
      { name: "Wrench", label: "Инструмент" },
      { name: "Hammer", label: "Молоток" },
      { name: "Cog", label: "Настройки" },
      { name: "Settings2", label: "Параметры" },
      { name: "LayoutDashboard", label: "Дашборд" },
      { name: "LayoutGrid", label: "Сетка" },
      { name: "Kanban", label: "Канбан" },
      { name: "ListTodo", label: "Задачи" },
      { name: "ClipboardList", label: "Чек-лист" },
      { name: "Briefcase", label: "Проекты" },
      { name: "Target", label: "Цели" },
      { name: "Workflow", label: "Процессы" },
    ],
  },
  {
    group: "Аналитика",
    items: [
      { name: "BarChart3", label: "Аналитика" },
      { name: "BarChart4", label: "Отчёты" },
      { name: "LineChart", label: "График" },
      { name: "PieChart", label: "Диаграмма" },
      { name: "TrendingUp", label: "Рост" },
      { name: "TrendingDown", label: "Падение" },
      { name: "Activity", label: "Активность" },
      { name: "Gauge", label: "Метрики" },
      { name: "Table2", label: "Таблица" },
      { name: "Percent", label: "Проценты" },
    ],
  },
  {
    group: "Люди",
    items: [
      { name: "Users", label: "Команда" },
      { name: "User", label: "Профиль" },
      { name: "UserCheck", label: "CRM" },
      { name: "UserPlus", label: "Найм" },
      { name: "Contact", label: "Контакты" },
      { name: "Building2", label: "Компания" },
      { name: "Handshake", label: "Партнёры" },
      { name: "Headset", label: "Поддержка" },
      { name: "GraduationCap", label: "Обучение" },
      { name: "Award", label: "Награды" },
    ],
  },
  {
    group: "Связь",
    items: [
      { name: "Mail", label: "Почта" },
      { name: "MessageSquare", label: "Чат" },
      { name: "MessagesSquare", label: "Диалоги" },
      { name: "Send", label: "Отправка" },
      { name: "Phone", label: "Телефон" },
      { name: "PhoneCall", label: "Звонки" },
      { name: "Video", label: "Видео" },
      { name: "Mic", label: "Аудио" },
      { name: "Megaphone", label: "Анонсы" },
      { name: "Bell", label: "Уведомления" },
      { name: "AtSign", label: "Упоминания" },
      { name: "Rss", label: "Лента" },
    ],
  },
  {
    group: "Документы",
    items: [
      { name: "FileText", label: "Документы" },
      { name: "FileSpreadsheet", label: "Таблицы" },
      { name: "FileCode2", label: "Код-файл" },
      { name: "FileSignature", label: "Договор" },
      { name: "Files", label: "Архив" },
      { name: "FolderOpen", label: "Файлы" },
      { name: "BookOpen", label: "База знаний" },
      { name: "Notebook", label: "Заметки" },
      { name: "Scale", label: "Юридические" },
      { name: "Stamp", label: "Печать" },
      { name: "Printer", label: "Печать док." },
      { name: "ScrollText", label: "Логи" },
    ],
  },
  {
    group: "Разработка",
    items: [
      { name: "Code2", label: "Код" },
      { name: "Terminal", label: "Терминал" },
      { name: "Bug", label: "Баг-трекер" },
      { name: "GitBranch", label: "Репозиторий" },
      { name: "GitMerge", label: "Мердж" },
      { name: "Database", label: "База данных" },
      { name: "Server", label: "Сервер" },
      { name: "Cloud", label: "Облако" },
      { name: "Container", label: "Контейнеры" },
      { name: "Cpu", label: "Инфраструктура" },
      { name: "Binary", label: "Данные" },
      { name: "Webhook", label: "Вебхуки" },
      { name: "Blocks", label: "Модули" },
      { name: "Puzzle", label: "Плагины" },
    ],
  },
  {
    group: "Маркетинг",
    items: [
      { name: "Globe", label: "Сайт" },
      { name: "Link2", label: "Ссылка" },
      { name: "Search", label: "Поиск / SEO" },
      { name: "Rocket", label: "Запуск" },
      { name: "Flame", label: "Тренды" },
      { name: "Tag", label: "Метки" },
      { name: "Gift", label: "Акции" },
      { name: "Store", label: "Витрина" },
      { name: "ShoppingCart", label: "Магазин" },
      { name: "Package", label: "Товары" },
      { name: "Truck", label: "Доставка" },
      { name: "Palette", label: "Дизайн" },
      { name: "Image", label: "Медиа" },
      { name: "Film", label: "Видеопродакшн" },
      { name: "PenTool", label: "Иллюстрация" },
      { name: "Brush", label: "Креатив" },
    ],
  },
  {
    group: "Финансы",
    items: [
      { name: "CreditCard", label: "Платежи" },
      { name: "Wallet", label: "Финансы" },
      { name: "Banknote", label: "Наличные" },
      { name: "Coins", label: "Монеты" },
      { name: "Receipt", label: "Счета" },
      { name: "Calculator", label: "Калькулятор" },
      { name: "Landmark", label: "Банк" },
      { name: "PiggyBank", label: "Бюджет" },
    ],
  },
  {
    group: "Время",
    items: [
      { name: "CalendarDays", label: "Календарь" },
      { name: "CalendarClock", label: "Расписание" },
      { name: "CalendarCheck", label: "Планы" },
      { name: "Clock", label: "Время" },
      { name: "Timer", label: "Таймер" },
      { name: "AlarmClock", label: "Напоминания" },
      { name: "Hourglass", label: "Дедлайн" },
      { name: "History", label: "История" },
    ],
  },
  {
    group: "Безопасность",
    items: [
      { name: "ShieldCheck", label: "Безопасность" },
      { name: "Shield", label: "Защита" },
      { name: "KeyRound", label: "Доступы" },
      { name: "Lock", label: "Замок" },
      { name: "Fingerprint", label: "Идентификация" },
      { name: "EyeOff", label: "Приватность" },
      { name: "ScanFace", label: "Биометрия" },
    ],
  },
  {
    group: "Прочее",
    items: [
      { name: "Sparkles", label: "AI" },
      { name: "Bot", label: "Бот" },
      { name: "BrainCircuit", label: "Нейросеть" },
      { name: "Zap", label: "Быстро" },
      { name: "Star", label: "Избранное" },
      { name: "Heart", label: "Любимое" },
      { name: "Compass", label: "Навигация" },
      { name: "MapPin", label: "Локация" },
      { name: "Map", label: "Карта" },
      { name: "Plane", label: "Командировки" },
      { name: "Coffee", label: "Отдых" },
      { name: "Lightbulb", label: "Идеи" },
      { name: "Boxes", label: "Склад" },
      { name: "Recycle", label: "Процессинг" },
      { name: "Smile", label: "Настроение" },
      { name: "Trophy", label: "Достижения" },
    ],
  },
];

/** Плоский список всех lucide-иконок пака. */
export const ICON_PACK: IconItem[] = ICON_GROUPS.flatMap((g) => g.items);

/** Цветные эмодзи-иконки: хранятся как "emoji:🧮". */
export const EMOJI_PACK: IconItem[] = [
  "🧮","📊","📈","📉","🗂","📁","📝","📌","📅","⏱","⏰","🔔","💡","🚀","🔥","⭐","🎯","🏆",
  "🤖","🧠","⚙️","🔧","🔨","🧰","🛠","🔑","🔒","🛡","🧪","🔬","🧭","🗺","📍","✈️","🚚","📦",
  "💳","💰","🧾","🏦","💼","🏢","👥","👤","🤝","🎧","📞","✉️","💬","📣","🌐","🔗","🖥","💻",
  "📱","🗄","☁️","🧩","🎨","🖌","🖼","🎬","🎥","🎵","🛒","🏬","🎁","📚","📖","⚖️","✅","❤️",
].map((e) => ({ name: `emoji:${e}`, label: e }));
