/** 40 curated lucide icons offered as the MTools icon pack for tools & services. */
export const ICON_PACK: { name: string; label: string }[] = [
  { name: "Wrench", label: "Инструмент" },
  { name: "LayoutDashboard", label: "Дашборд" },
  { name: "BarChart3", label: "Аналитика" },
  { name: "PieChart", label: "Диаграмма" },
  { name: "TrendingUp", label: "Рост" },
  { name: "Users", label: "Команда" },
  { name: "UserCheck", label: "CRM" },
  { name: "Building2", label: "Компания" },
  { name: "Briefcase", label: "Проекты" },
  { name: "ListTodo", label: "Задачи" },
  { name: "CalendarDays", label: "Календарь" },
  { name: "Clock", label: "Время" },
  { name: "Timer", label: "Таймер" },
  { name: "Mail", label: "Почта" },
  { name: "MessageSquare", label: "Чат" },
  { name: "Send", label: "Отправка" },
  { name: "Phone", label: "Телефон" },
  { name: "Video", label: "Видео" },
  { name: "FileText", label: "Документы" },
  { name: "FolderOpen", label: "Файлы" },
  { name: "Database", label: "База данных" },
  { name: "Server", label: "Сервер" },
  { name: "Cloud", label: "Облако" },
  { name: "Globe", label: "Сайт" },
  { name: "Link2", label: "Ссылка" },
  { name: "Code2", label: "Код" },
  { name: "Terminal", label: "Терминал" },
  { name: "Bug", label: "Баг-трекер" },
  { name: "GitBranch", label: "Репозиторий" },
  { name: "Palette", label: "Дизайн" },
  { name: "Image", label: "Медиа" },
  { name: "ShoppingCart", label: "Магазин" },
  { name: "CreditCard", label: "Платежи" },
  { name: "Wallet", label: "Финансы" },
  { name: "Calculator", label: "Калькулятор" },
  { name: "ShieldCheck", label: "Безопасность" },
  { name: "KeyRound", label: "Доступы" },
  { name: "Bell", label: "Уведомления" },
  { name: "BookOpen", label: "База знаний" },
  { name: "Sparkles", label: "AI" },
];
